input: /data/Daan/Projects/INRB_TST2/Input/mpox.csv
outdir: /data/Daan/Projects/INRB_TST2/Output
fasta: /data/Daan/Projects/nextflow-metatropics-INRB/Databases/Human/chm13v2.0.fa
dbmeta: /data/Daan/Projects/nextflow-metatropics-INRB/Databases/ViralRefseq
minLength: 200
pair: true
front: 18
tail: 18
minVirus: 0.01
quality: 20
depth: 5
agreement: 0.7
