input: /data/Daan/Projects/INRB/Input/mpox.csv # csv files is different for fast5 and fastq files
outdir: /data/Daan/Projects/INRB/Output
fasta: /data/Daan/Projects/nextflow-metatropics-INRB/Databases/Human/chm13v2.0.fa
#host_fasta: /data/Daan/Projects/nextflow-metatropics-INRB/Databases/Aedes/Aedes_aegypti.fasta
dbmeta: /data/Daan/Projects/nextflow-metatropics-INRB/Databases/ViralRefseq
minLength: 200
pair: true
front: 18
tail: 18
minVirus: 0.01
quality: 20
depth: 5
agreement: 0.7
rcoverage_figure: true
